### PR TITLE
Macro

### LINKED ISSUE #42: Macro inspired by ember-i18n
I think the macro idea from `ember-i18n` is really neat: https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text#translation-computed-property-macro

It would be nice to have that here too. For now I ported the code to my project but if it is something you want maybe I can work on a PR.

### PR DESCRIPTION
**Pull request by karellm**
- [x] Add a macro - 5e564f0

I know you wanted the macro to take a list of arguments but I don't think it is possible. To support interpolation, we need to pass multiple `key:value` pairs.

Closes #42

### CODE REVIEW

**Comment by karellm** [comment]
Some tests are failing on older versions because of `ember-source`. I'm still trying to figure that one out.

**Comment by karellm** [comment]
@kirenotneb Can you please address commit per commit your position on whether you want it or not and why? I don't mind splitting this in multiple PRs but the first question is whether or not the changes are wanted. 

There are many changes but if you look at individual commits, it is easier to review.

**Comment by kirenotneb** [comment]
@karellm commit https://github.com/OCTRI/ember-i18next/commit/c67a6937b28672ccda5e1c5e3db4ae3886107498 is the one we would like to move forward with. I agree that they can be reviewed commit by commit, but we are not ready to upgrade to Ember 3 at present.

**Comment by karellm** [comment]
I should have been clearer in my description that this was still a WIP. I don't expect you to merge this with a failing test case.

Removing `useYarn: true` was a mistake, now Travis pass. But it does because it doesn't actually test `1.13`. Removing `1.13` wasn't intentional either. It doesn't pass in this branch ([screenshot](https://user-images.githubusercontent.com/119841/37566832-abd8c21a-2a94-11e8-8dc4-7d4e9ed6ed5a.png)), but it doesn't seem to pass on master either as a FYI ([screenshot](https://user-images.githubusercontent.com/119841/37566851-f46eed56-2a94-11e8-9bc6-61083c3693a8.png)).

I'm still investigating why `1.13` is now failing, if it is actually incompatible or if it is only an `ember-try` issue. May I solve this issue, do you still want me to split this PR in two?

**Comment by heathharrelson** [comment]
We'd still like you to split the PR on the grounds that it mixes two undesired changes in with the work to add the macro. We want to respect the time you've put into the PR, but we'd also like you to respect the time we will spend reviewing.

I checked out master and ran the scenario for Ember 1.13, and the only test failure is caused by the missing super call in the `init` method of `addon/services/i18n.js`, which would actually be fixed by this PR.

According to [this year's Ember Community Survey](https://www.emberjs.com/ember-community-survey-2018/), 8% of developers are still reporting working on Ember 1.13 applications, and so long as it's relatively simple to support 1.13, I don't see a compelling reason to drop it.

**Comment by karellm** [comment]
> We'd still like you to split the PR on the grounds that it mixes undesired changes in with the work to add the macro. We want to respect the time you've put into the PR, but we'd also like you to respect the time we will spend reviewing.

@heathharrelson Since I plan on working on this addon more (it would be silly to duplicate addons), I was wondering if there is something I said that made you think that I was not respecting your time? 

If it is related to single purpose PRs, we might simply come from different workflows. I'm used to working with a team that rewrites commits in order to actually make the review process extremely simple. To us single purpose commits are more important than single purpose PRs (even though it also is important). In all cases, I will split this PR once `1.13` passes and follow that rule in the future.

**Comment by kirenotneb** [comment]
@karellm I agree that this is probably a simple difference in team culture. "Disrespect" may be too strong of word. Our practice is to provide targeted PRs to limit the scope of change, which may combine multiple commits but focuses on the specific task at hand, rather than combining different things all at once. This provides better context and in our experience leads to better reviews since we aren't distracted by details that are unrelated to the specific change being introduced. While both styles are valid, we prefer to operate in this fashion for the aforementioned reasons. Thanks for you continued interest in moving this forward.

**Comment by karellm** [comment]
@kirenotneb @heathharrelson I've talked with the core team. `ember-test-helpers` dropped support for `ember@1.13` with version `0.7.0`. 

The error that we currently get running `ember try:one ember-1.13.13` does not mean that the tests don't pass, just that there is an incompatibility booting the app from 1.13 ember apps. See the details in this [slack conversation](https://embercommunity.slack.com/archives/C045C9ABM/p1521725286000185).

I see two course of actions:
- A/ Bump the version of this addon and drop support for `1.13`. As much as it is used, this addon is stable and good to be used as is. People on `1.13` can stick with version `1.0.0`. Plus it doesn't mean that 8% of the apps using this addon are actually on `1.13`.  I would vote for this, I think that it is one of the beauty of Ember to keep improving while providing clean update guidelines. `1.13` is really old at this point, it shouldn't prevent us from using the great improvements in Ember!
- B/ Keep the old ember test API while still updating to `ember@3.0`. This would need to be tested.

**Comment by karellm** [comment]
Why do you close a PR that is flagged [WIP] with meaningful conversations and work? Updating to `3.0` is NOT the issue, the new test API is. And I said I would split the work of the macro in a separate PR...  

The atmosphere here is starting to be very unwelcoming. Do you actually care for collaborations or should I build my own add-on?

**Comment by karellm** [comment]
@kirenotneb I understand that you have limited resources and time to put in this. I've had times when maintaining OSS and managing collaborators was challenging. My intention is clearly not to storm through this addon. I will follow the guidelines if you make them clear. I just found weird closing a "WIP" PR where all the discussions are.

Anyway, no hard feelings here. Let's start again with a fresh mind. I just published a separate PR with just Ember 3.0 and passing tests. I will rebase this one once #54 is merged and make sure it has a single purpose.

**Comment by kirenotneb** [comment]
I think I see the confusion. We want to marco first and followed by the changes to testing and Ember 3, not the other way around. It should be a straight forward effort to provide the macro, its specific tests and docs since the scope of that change is limited.

**Comment by karellm** [comment]
@kirenotneb Ok. You suggested making 2 PRs, since the work was done in that order, I kept it the way it was. For the sake of moving forward and respecting every one's time, now that it is done and ready to review, can you please proceed with #54 ?

**Comment by karellm** [comment]
@kirenotneb @heathharrelson Rebased and single committed. Ready to review. I updated the top description too.

**Comment by heathharrelson** [comment]
@karellm Thanks for the cleanup. I'm going to merge this now, and I'll work get out a 2.1 release with this feature this week.

**Comment by karellm** [comment]
@heathharrelson Is it possible to get the release please? Thanks

**Comment by heathharrelson** [comment]
@karellm Released version 2.1.0.

**Pull request merged**
